version: "3.1"

services:
  app:
    image: node:8.4-alpine
    command: sh -c "npm install && npm start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app:rw,cached
    environment:
      REACT_APP_API_URL: http://localhost:8080
