
export const APP_INIT = "APP_INIT";
export const SET_AUTHENTICATION = "SET_AUTHENTICATION";
export const CHECK_AUTHORIZATION = "CHECK_AUTHORIZATION";
export const AUTHENTICATION_FAILURE = "AUTHENTICATION_FAILURE";
export const SIGN_OUT = "SIGN_OUT";
export const SET_SESSIONS = "SET_SESSIONS";

export const SUBMIT_FEEDBACK = "SUBMIT_FEEDBACK";
export const FEEDBACK_FAILURE = "FEEDBACK_FAILURE";
export const FEEDBACK_SUCCESS = "FEEDBACK_SUCCESS";
